id = "sqlc-snippets"
name = "sqlc Snippets"
version = "0.2.0"
schema_version = 1
authors = ["RajaSunrise <indra020204@gmail.com>"]
description = "Sqlc and PostgreSQL snippets for Zed IDE."
repository = "https://github.com/NarmadaWeb/sqlc-snippets-zed"

snippets = "./snippets/sql.json"
